# credit https://medium.com/better-programming/deploy-your-gatsby-site-with-github-actions-e761ea93813f
# https://github.com/enriikke/gatsby-gh-pages-action/blob/main/README.md
name: Publish Gatsby to GitHub pages

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
    steps:
      - uses: actions/checkout@master

      - uses: enriikke/gatsby-gh-pages-action@v2
      # https://github.com/enriikke/gatsby-gh-pages-action/releases
      # source https://github.com/enriikke/gatsby-gh-pages-action/blob/main/index.ts
        with:
          # access-token is a GitHub Personal access token with the "repo" scope
          access-token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          deploy-branch: gh-pages

